#include <gssapi/gssapi.h>

OM_uint32 GSS_C_DELEG_FLAG_SHIM = GSS_C_DELEG_FLAG;
OM_uint32 GSS_C_MUTUAL_FLAG_SHIM = GSS_C_MUTUAL_FLAG;
OM_uint32 GSS_C_REPLAY_FLAG_SHIM = GSS_C_REPLAY_FLAG;
OM_uint32 GSS_C_SEQUENCE_FLAG_SHIM = GSS_C_SEQUENCE_FLAG;
OM_uint32 GSS_C_CONF_FLAG_SHIM = GSS_C_CONF_FLAG;
OM_uint32 GSS_C_INTEG_FLAG_SHIM = GSS_C_INTEG_FLAG;
OM_uint32 GSS_C_ANON_FLAG_SHIM = GSS_C_ANON_FLAG;
OM_uint32 GSS_C_PROT_READY_FLAG_SHIM = GSS_C_PROT_READY_FLAG;
OM_uint32 GSS_C_TRANS_FLAG_SHIM = GSS_C_TRANS_FLAG;
OM_uint32 GSS_C_DELEG_POLICY_FLAG_SHIM = GSS_C_DELEG_POLICY_FLAG;
OM_uint32 GSS_C_NO_UI_FLAG_SHIM = GSS_C_NO_UI_FLAG;

OM_uint32 GSS_C_GSS_CODE_SHIM = GSS_C_GSS_CODE;
OM_uint32 GSS_C_MECH_CODE_SHIM = GSS_C_MECH_CODE;

OM_uint32 GSS_S_COMPLETE_SHIM = GSS_S_COMPLETE;
OM_uint32 GSS_S_CONTINUE_NEEDED_SHIM = GSS_S_CONTINUE_NEEDED;
