/* automatically generated by rust-bindgen */

#![allow(non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]

#[link(name = "Kerberos", kind = "framework")]
#[cfg(target_os = "macos")]
extern { }

mod defines;
pub use defines::*;

mod gssapi_h;
pub use gssapi_h::*;

#[cfg(feature = "gssapi_ext")]
mod gssapi_ext_h;

#[cfg(feature = "gssapi_ext")]
pub use gssapi_ext_h::*;
